### ISSUE TITLE
卡死在miniupnp的设置上

### ISSUE THREAD

**Issue by mazzond** [jiaopengzi/build-openwrt#1]
Ubuntu 24.04LTS，自动安装。一上来就卡死在miniupnp了。。。不知道是为什么原因。。。
immortalwrt的编译难度比lede高了n倍。。。

**Comment by jiaopengzi** [comment]
你可以退出来脚本，手动安装 `sudo apt install -y miniupnpd`,再重新装跑编译脚本。
